name = "meshjs/aiken-workspace"
version = "0.0.0"
compiler = "v1.0.28-alpha"
plutus = "v2"
license = "Apache-2.0"
description = "Aiken contracts for project 'meshjs/aiken-workspace'"

[repository]
user = "meshjs"
project = "aiken-workspace"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
